---
---

<center><h1> 📍 📍 Basics of NumPy 📍 📍 </h1></center>


NumPy is the fundamental package for scientific computing with Python. It contains among other things:
 
 - A powerful N-dimensional array object
 - Sophisticated (broadcasting) functions
 - Tools for integrating C/C++ and Fortran code
 - Useful linear algebra, Fourier transform, and random number capabilities

***Source:*** https://numpy.org/

---

In [1]:
# importing the numpy library
import numpy as np

***If you got an error while running the above cell, import it by using the following command***


***`!pip3 install numpy`***

---

In [2]:
# check verison of the numpy library
np.__version__

'1.21.5'

In [3]:
# create a numpy array
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [4]:
[1,4,'2',5,False]

[1, 4, '2', 5, False]

***[1]    Difference between numpy array and list***

- Data type should be same of all the elements in a numpy array whereas it can be different in case of lists.
- **Broadcasting:** https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

---

In [5]:
# if we add an element of string data type in a numpy array
# then it will upcast the data type to string of all the elements.
np.array([1, 4, 2, '5', 3, False])

array(['1', '4', '2', '5', '3', 'False'], dtype='<U11')

***Now, we will create one sample list and numpy array and apply a very basic function of multiplication by 2. We will see that in case of list the elements are duplicated and appended to the list whereas in case of numpy array we got an array where all elements are multiplied by 2.***

----

In [6]:
# create a sample list
sample_list = [1, 2, 3, 4, 5, 6]

In [7]:
sample_list*2 

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [8]:
# create a sample numpy array
sample_numpy_array = np.array([1, 2, 3, 4, 5, 6])

In [9]:
sample_numpy_array+2

array([3, 4, 5, 6, 7, 8])

---

***[2] Create a matrix using numpy***

---

In [10]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

In [11]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
# MATRIX
a = np.array(a)

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[0][1]

2

In [15]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---

***[3]Data type and Type casting***

---

In [19]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [20]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [21]:
arr = np.array([True,False])

print(arr.dtype)

bool


---

***[4] Indexing and slicing***

---

In [16]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [17]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1][4])

10


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:1])

[2 3 4 5]


---

***[5]Array Shape and Array Reshap***

---

In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


---

***[6] Create a matrix of different types***

---

***[6.1] Create a matrix of `Zeros` of specific dimension.***


---

In [24]:
# Create a 2 X 10 integer array filled with zeros
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
# Create a 4 X 5 integer array filled with zeros
np.zeros((4,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

***[6.2] Create a matrix of `Ones` of specific dimension.***

---

In [26]:
# Create a 2 X 10 integer array filled with ones
np.ones((2,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [27]:
# Create a 4 X 5 integer array filled with ones
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

***[6.3] Create a indentity matrix.***

---

In [28]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

***[6.5] Create a matrix of filled with any specific number of specific dimension.***

---

In [29]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [30]:
# Create a 2x4 array filled with 7
np.full((2, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

---

***[7] Sorting Arrays***

---

In [31]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [32]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]




---
***[8] Array Concatenation :***


---



In [33]:
# concatenating 2-D arrays
matrix1 = np.array([[1, 2, 3], 
                    [4, 5, 6]])
print("matrix 1")
matrix1

matrix 1


array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
matrix2 = np.array([[7, 8, 9], 
                    [10, 11, 12]])
print("matrix 2",)
matrix2

matrix 2


array([[ 7,  8,  9],
       [10, 11, 12]])

***[8.1] Concatenate Row wise***

---

In [35]:
# concatenate along the first axis
matrix_1_2_combineRowwise = np.concatenate([matrix1, matrix2],axis=0)
print("Combined on Row (axis=0)")
matrix_1_2_combineRowwise

Combined on Row (axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

***[8.2] Concatenate Column wise***


---

In [36]:
# concatenate along the second axis (zero-indexed)
matrix_1_2_combineColwise = np.concatenate([matrix1, matrix2], axis=1)
print("Combined on Col (axis=1)")
matrix_1_2_combineColwise

Combined on Col (axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

***Learn more about the numpy here: https://numpy.org/doc/1.17/user/index.html***

---

---

***[9]Split Array***

---

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


---

***[10] Copy Aaray***

---

In [40]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


---

***[11] Search Aaray***

---

In [38]:
#You can search an array for a certain value, and return the indexes that get a match.
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)
